// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: EpidemicPayload.proto

// Protobuf Java Version: 3.25.2
package ca.NetSysLab.ProtocolBuffers;

public final class EpidemicPayload {
  private EpidemicPayload() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface EpidemicPldOrBuilder extends
      // @@protoc_insertion_point(interface_extends:EpidemicPld)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>fixed32 nodeID = 1;</code>
     * @return The nodeID.
     */
    int getNodeID();

    /**
     * <code>fixed64 timestamp = 2;</code>
     * @return The timestamp.
     */
    long getTimestamp();

    /**
     * <code>double propagationProbability = 3;</code>
     * @return The propagationProbability.
     */
    double getPropagationProbability();
  }
  /**
   * Protobuf type {@code EpidemicPld}
   */
  public static final class EpidemicPld extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:EpidemicPld)
      EpidemicPldOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use EpidemicPld.newBuilder() to construct.
    private EpidemicPld(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private EpidemicPld() {
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new EpidemicPld();
    }

    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return ca.NetSysLab.ProtocolBuffers.EpidemicPayload.internal_static_EpidemicPld_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return ca.NetSysLab.ProtocolBuffers.EpidemicPayload.internal_static_EpidemicPld_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              ca.NetSysLab.ProtocolBuffers.EpidemicPayload.EpidemicPld.class, ca.NetSysLab.ProtocolBuffers.EpidemicPayload.EpidemicPld.Builder.class);
    }

    public static final int NODEID_FIELD_NUMBER = 1;
    private int nodeID_ = 0;
    /**
     * <code>fixed32 nodeID = 1;</code>
     * @return The nodeID.
     */
    @java.lang.Override
    public int getNodeID() {
      return nodeID_;
    }

    public static final int TIMESTAMP_FIELD_NUMBER = 2;
    private long timestamp_ = 0L;
    /**
     * <code>fixed64 timestamp = 2;</code>
     * @return The timestamp.
     */
    @java.lang.Override
    public long getTimestamp() {
      return timestamp_;
    }

    public static final int PROPAGATIONPROBABILITY_FIELD_NUMBER = 3;
    private double propagationProbability_ = 0D;
    /**
     * <code>double propagationProbability = 3;</code>
     * @return The propagationProbability.
     */
    @java.lang.Override
    public double getPropagationProbability() {
      return propagationProbability_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (nodeID_ != 0) {
        output.writeFixed32(1, nodeID_);
      }
      if (timestamp_ != 0L) {
        output.writeFixed64(2, timestamp_);
      }
      if (java.lang.Double.doubleToRawLongBits(propagationProbability_) != 0) {
        output.writeDouble(3, propagationProbability_);
      }
      getUnknownFields().writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (nodeID_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeFixed32Size(1, nodeID_);
      }
      if (timestamp_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeFixed64Size(2, timestamp_);
      }
      if (java.lang.Double.doubleToRawLongBits(propagationProbability_) != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeDoubleSize(3, propagationProbability_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof ca.NetSysLab.ProtocolBuffers.EpidemicPayload.EpidemicPld)) {
        return super.equals(obj);
      }
      ca.NetSysLab.ProtocolBuffers.EpidemicPayload.EpidemicPld other = (ca.NetSysLab.ProtocolBuffers.EpidemicPayload.EpidemicPld) obj;

      if (getNodeID()
          != other.getNodeID()) return false;
      if (getTimestamp()
          != other.getTimestamp()) return false;
      if (java.lang.Double.doubleToLongBits(getPropagationProbability())
          != java.lang.Double.doubleToLongBits(
              other.getPropagationProbability())) return false;
      if (!getUnknownFields().equals(other.getUnknownFields())) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + NODEID_FIELD_NUMBER;
      hash = (53 * hash) + getNodeID();
      hash = (37 * hash) + TIMESTAMP_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getTimestamp());
      hash = (37 * hash) + PROPAGATIONPROBABILITY_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          java.lang.Double.doubleToLongBits(getPropagationProbability()));
      hash = (29 * hash) + getUnknownFields().hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static ca.NetSysLab.ProtocolBuffers.EpidemicPayload.EpidemicPld parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static ca.NetSysLab.ProtocolBuffers.EpidemicPayload.EpidemicPld parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static ca.NetSysLab.ProtocolBuffers.EpidemicPayload.EpidemicPld parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static ca.NetSysLab.ProtocolBuffers.EpidemicPayload.EpidemicPld parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static ca.NetSysLab.ProtocolBuffers.EpidemicPayload.EpidemicPld parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static ca.NetSysLab.ProtocolBuffers.EpidemicPayload.EpidemicPld parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static ca.NetSysLab.ProtocolBuffers.EpidemicPayload.EpidemicPld parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static ca.NetSysLab.ProtocolBuffers.EpidemicPayload.EpidemicPld parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public static ca.NetSysLab.ProtocolBuffers.EpidemicPayload.EpidemicPld parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }

    public static ca.NetSysLab.ProtocolBuffers.EpidemicPayload.EpidemicPld parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static ca.NetSysLab.ProtocolBuffers.EpidemicPayload.EpidemicPld parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static ca.NetSysLab.ProtocolBuffers.EpidemicPayload.EpidemicPld parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(ca.NetSysLab.ProtocolBuffers.EpidemicPayload.EpidemicPld prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code EpidemicPld}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:EpidemicPld)
        ca.NetSysLab.ProtocolBuffers.EpidemicPayload.EpidemicPldOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return ca.NetSysLab.ProtocolBuffers.EpidemicPayload.internal_static_EpidemicPld_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return ca.NetSysLab.ProtocolBuffers.EpidemicPayload.internal_static_EpidemicPld_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                ca.NetSysLab.ProtocolBuffers.EpidemicPayload.EpidemicPld.class, ca.NetSysLab.ProtocolBuffers.EpidemicPayload.EpidemicPld.Builder.class);
      }

      // Construct using ca.NetSysLab.ProtocolBuffers.EpidemicPayload.EpidemicPld.newBuilder()
      private Builder() {

      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);

      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        bitField0_ = 0;
        nodeID_ = 0;
        timestamp_ = 0L;
        propagationProbability_ = 0D;
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return ca.NetSysLab.ProtocolBuffers.EpidemicPayload.internal_static_EpidemicPld_descriptor;
      }

      @java.lang.Override
      public ca.NetSysLab.ProtocolBuffers.EpidemicPayload.EpidemicPld getDefaultInstanceForType() {
        return ca.NetSysLab.ProtocolBuffers.EpidemicPayload.EpidemicPld.getDefaultInstance();
      }

      @java.lang.Override
      public ca.NetSysLab.ProtocolBuffers.EpidemicPayload.EpidemicPld build() {
        ca.NetSysLab.ProtocolBuffers.EpidemicPayload.EpidemicPld result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public ca.NetSysLab.ProtocolBuffers.EpidemicPayload.EpidemicPld buildPartial() {
        ca.NetSysLab.ProtocolBuffers.EpidemicPayload.EpidemicPld result = new ca.NetSysLab.ProtocolBuffers.EpidemicPayload.EpidemicPld(this);
        if (bitField0_ != 0) { buildPartial0(result); }
        onBuilt();
        return result;
      }

      private void buildPartial0(ca.NetSysLab.ProtocolBuffers.EpidemicPayload.EpidemicPld result) {
        int from_bitField0_ = bitField0_;
        if (((from_bitField0_ & 0x00000001) != 0)) {
          result.nodeID_ = nodeID_;
        }
        if (((from_bitField0_ & 0x00000002) != 0)) {
          result.timestamp_ = timestamp_;
        }
        if (((from_bitField0_ & 0x00000004) != 0)) {
          result.propagationProbability_ = propagationProbability_;
        }
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof ca.NetSysLab.ProtocolBuffers.EpidemicPayload.EpidemicPld) {
          return mergeFrom((ca.NetSysLab.ProtocolBuffers.EpidemicPayload.EpidemicPld)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(ca.NetSysLab.ProtocolBuffers.EpidemicPayload.EpidemicPld other) {
        if (other == ca.NetSysLab.ProtocolBuffers.EpidemicPayload.EpidemicPld.getDefaultInstance()) return this;
        if (other.getNodeID() != 0) {
          setNodeID(other.getNodeID());
        }
        if (other.getTimestamp() != 0L) {
          setTimestamp(other.getTimestamp());
        }
        if (other.getPropagationProbability() != 0D) {
          setPropagationProbability(other.getPropagationProbability());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        if (extensionRegistry == null) {
          throw new java.lang.NullPointerException();
        }
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              case 13: {
                nodeID_ = input.readFixed32();
                bitField0_ |= 0x00000001;
                break;
              } // case 13
              case 17: {
                timestamp_ = input.readFixed64();
                bitField0_ |= 0x00000002;
                break;
              } // case 17
              case 25: {
                propagationProbability_ = input.readDouble();
                bitField0_ |= 0x00000004;
                break;
              } // case 25
              default: {
                if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                  done = true; // was an endgroup tag
                }
                break;
              } // default:
            } // switch (tag)
          } // while (!done)
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.unwrapIOException();
        } finally {
          onChanged();
        } // finally
        return this;
      }
      private int bitField0_;

      private int nodeID_ ;
      /**
       * <code>fixed32 nodeID = 1;</code>
       * @return The nodeID.
       */
      @java.lang.Override
      public int getNodeID() {
        return nodeID_;
      }
      /**
       * <code>fixed32 nodeID = 1;</code>
       * @param value The nodeID to set.
       * @return This builder for chaining.
       */
      public Builder setNodeID(int value) {

        nodeID_ = value;
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }
      /**
       * <code>fixed32 nodeID = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearNodeID() {
        bitField0_ = (bitField0_ & ~0x00000001);
        nodeID_ = 0;
        onChanged();
        return this;
      }

      private long timestamp_ ;
      /**
       * <code>fixed64 timestamp = 2;</code>
       * @return The timestamp.
       */
      @java.lang.Override
      public long getTimestamp() {
        return timestamp_;
      }
      /**
       * <code>fixed64 timestamp = 2;</code>
       * @param value The timestamp to set.
       * @return This builder for chaining.
       */
      public Builder setTimestamp(long value) {

        timestamp_ = value;
        bitField0_ |= 0x00000002;
        onChanged();
        return this;
      }
      /**
       * <code>fixed64 timestamp = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearTimestamp() {
        bitField0_ = (bitField0_ & ~0x00000002);
        timestamp_ = 0L;
        onChanged();
        return this;
      }

      private double propagationProbability_ ;
      /**
       * <code>double propagationProbability = 3;</code>
       * @return The propagationProbability.
       */
      @java.lang.Override
      public double getPropagationProbability() {
        return propagationProbability_;
      }
      /**
       * <code>double propagationProbability = 3;</code>
       * @param value The propagationProbability to set.
       * @return This builder for chaining.
       */
      public Builder setPropagationProbability(double value) {

        propagationProbability_ = value;
        bitField0_ |= 0x00000004;
        onChanged();
        return this;
      }
      /**
       * <code>double propagationProbability = 3;</code>
       * @return This builder for chaining.
       */
      public Builder clearPropagationProbability() {
        bitField0_ = (bitField0_ & ~0x00000004);
        propagationProbability_ = 0D;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:EpidemicPld)
    }

    // @@protoc_insertion_point(class_scope:EpidemicPld)
    private static final ca.NetSysLab.ProtocolBuffers.EpidemicPayload.EpidemicPld DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new ca.NetSysLab.ProtocolBuffers.EpidemicPayload.EpidemicPld();
    }

    public static ca.NetSysLab.ProtocolBuffers.EpidemicPayload.EpidemicPld getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<EpidemicPld>
        PARSER = new com.google.protobuf.AbstractParser<EpidemicPld>() {
      @java.lang.Override
      public EpidemicPld parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        Builder builder = newBuilder();
        try {
          builder.mergeFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(builder.buildPartial());
        } catch (com.google.protobuf.UninitializedMessageException e) {
          throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(e)
              .setUnfinishedMessage(builder.buildPartial());
        }
        return builder.buildPartial();
      }
    };

    public static com.google.protobuf.Parser<EpidemicPld> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<EpidemicPld> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public ca.NetSysLab.ProtocolBuffers.EpidemicPayload.EpidemicPld getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_EpidemicPld_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_EpidemicPld_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\025EpidemicPayload.proto\"P\n\013EpidemicPld\022\016" +
      "\n\006nodeID\030\001 \001(\007\022\021\n\ttimestamp\030\002 \001(\006\022\036\n\026pro" +
      "pagationProbability\030\003 \001(\001B/\n\034ca.NetSysLa" +
      "b.ProtocolBuffersB\017EpidemicPayloadb\006prot" +
      "o3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_EpidemicPld_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_EpidemicPld_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_EpidemicPld_descriptor,
        new java.lang.String[] { "NodeID", "Timestamp", "PropagationProbability", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
