// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ForwardedMessage.proto

// Protobuf Java Version: 3.25.2
package ca.NetSysLab.ProtocolBuffers;

public final class ForwardedMessage {
  private ForwardedMessage() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface FwdMsgOrBuilder extends
      // @@protoc_insertion_point(interface_extends:FwdMsg)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>bytes clientMessageId = 1;</code>
     * @return The clientMessageId.
     */
    com.google.protobuf.ByteString getClientMessageId();

    /**
     * <code>bytes clientRequest = 2;</code>
     * @return The clientRequest.
     */
    com.google.protobuf.ByteString getClientRequest();

    /**
     * <code>fixed32 clientPort = 3;</code>
     * @return The clientPort.
     */
    int getClientPort();

    /**
     * <code>string clientIP = 4;</code>
     * @return The clientIP.
     */
    java.lang.String getClientIP();
    /**
     * <code>string clientIP = 4;</code>
     * @return The bytes for clientIP.
     */
    com.google.protobuf.ByteString
        getClientIPBytes();
  }
  /**
   * Protobuf type {@code FwdMsg}
   */
  public static final class FwdMsg extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:FwdMsg)
      FwdMsgOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use FwdMsg.newBuilder() to construct.
    private FwdMsg(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private FwdMsg() {
      clientMessageId_ = com.google.protobuf.ByteString.EMPTY;
      clientRequest_ = com.google.protobuf.ByteString.EMPTY;
      clientIP_ = "";
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new FwdMsg();
    }

    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return ca.NetSysLab.ProtocolBuffers.ForwardedMessage.internal_static_FwdMsg_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return ca.NetSysLab.ProtocolBuffers.ForwardedMessage.internal_static_FwdMsg_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              ca.NetSysLab.ProtocolBuffers.ForwardedMessage.FwdMsg.class, ca.NetSysLab.ProtocolBuffers.ForwardedMessage.FwdMsg.Builder.class);
    }

    public static final int CLIENTMESSAGEID_FIELD_NUMBER = 1;
    private com.google.protobuf.ByteString clientMessageId_ = com.google.protobuf.ByteString.EMPTY;
    /**
     * <code>bytes clientMessageId = 1;</code>
     * @return The clientMessageId.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString getClientMessageId() {
      return clientMessageId_;
    }

    public static final int CLIENTREQUEST_FIELD_NUMBER = 2;
    private com.google.protobuf.ByteString clientRequest_ = com.google.protobuf.ByteString.EMPTY;
    /**
     * <code>bytes clientRequest = 2;</code>
     * @return The clientRequest.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString getClientRequest() {
      return clientRequest_;
    }

    public static final int CLIENTPORT_FIELD_NUMBER = 3;
    private int clientPort_ = 0;
    /**
     * <code>fixed32 clientPort = 3;</code>
     * @return The clientPort.
     */
    @java.lang.Override
    public int getClientPort() {
      return clientPort_;
    }

    public static final int CLIENTIP_FIELD_NUMBER = 4;
    @SuppressWarnings("serial")
    private volatile java.lang.Object clientIP_ = "";
    /**
     * <code>string clientIP = 4;</code>
     * @return The clientIP.
     */
    @java.lang.Override
    public java.lang.String getClientIP() {
      java.lang.Object ref = clientIP_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        clientIP_ = s;
        return s;
      }
    }
    /**
     * <code>string clientIP = 4;</code>
     * @return The bytes for clientIP.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getClientIPBytes() {
      java.lang.Object ref = clientIP_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        clientIP_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!clientMessageId_.isEmpty()) {
        output.writeBytes(1, clientMessageId_);
      }
      if (!clientRequest_.isEmpty()) {
        output.writeBytes(2, clientRequest_);
      }
      if (clientPort_ != 0) {
        output.writeFixed32(3, clientPort_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(clientIP_)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 4, clientIP_);
      }
      getUnknownFields().writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!clientMessageId_.isEmpty()) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(1, clientMessageId_);
      }
      if (!clientRequest_.isEmpty()) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(2, clientRequest_);
      }
      if (clientPort_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeFixed32Size(3, clientPort_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(clientIP_)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(4, clientIP_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof ca.NetSysLab.ProtocolBuffers.ForwardedMessage.FwdMsg)) {
        return super.equals(obj);
      }
      ca.NetSysLab.ProtocolBuffers.ForwardedMessage.FwdMsg other = (ca.NetSysLab.ProtocolBuffers.ForwardedMessage.FwdMsg) obj;

      if (!getClientMessageId()
          .equals(other.getClientMessageId())) return false;
      if (!getClientRequest()
          .equals(other.getClientRequest())) return false;
      if (getClientPort()
          != other.getClientPort()) return false;
      if (!getClientIP()
          .equals(other.getClientIP())) return false;
      if (!getUnknownFields().equals(other.getUnknownFields())) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + CLIENTMESSAGEID_FIELD_NUMBER;
      hash = (53 * hash) + getClientMessageId().hashCode();
      hash = (37 * hash) + CLIENTREQUEST_FIELD_NUMBER;
      hash = (53 * hash) + getClientRequest().hashCode();
      hash = (37 * hash) + CLIENTPORT_FIELD_NUMBER;
      hash = (53 * hash) + getClientPort();
      hash = (37 * hash) + CLIENTIP_FIELD_NUMBER;
      hash = (53 * hash) + getClientIP().hashCode();
      hash = (29 * hash) + getUnknownFields().hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static ca.NetSysLab.ProtocolBuffers.ForwardedMessage.FwdMsg parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static ca.NetSysLab.ProtocolBuffers.ForwardedMessage.FwdMsg parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static ca.NetSysLab.ProtocolBuffers.ForwardedMessage.FwdMsg parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static ca.NetSysLab.ProtocolBuffers.ForwardedMessage.FwdMsg parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static ca.NetSysLab.ProtocolBuffers.ForwardedMessage.FwdMsg parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static ca.NetSysLab.ProtocolBuffers.ForwardedMessage.FwdMsg parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static ca.NetSysLab.ProtocolBuffers.ForwardedMessage.FwdMsg parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static ca.NetSysLab.ProtocolBuffers.ForwardedMessage.FwdMsg parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public static ca.NetSysLab.ProtocolBuffers.ForwardedMessage.FwdMsg parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }

    public static ca.NetSysLab.ProtocolBuffers.ForwardedMessage.FwdMsg parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static ca.NetSysLab.ProtocolBuffers.ForwardedMessage.FwdMsg parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static ca.NetSysLab.ProtocolBuffers.ForwardedMessage.FwdMsg parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(ca.NetSysLab.ProtocolBuffers.ForwardedMessage.FwdMsg prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code FwdMsg}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:FwdMsg)
        ca.NetSysLab.ProtocolBuffers.ForwardedMessage.FwdMsgOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return ca.NetSysLab.ProtocolBuffers.ForwardedMessage.internal_static_FwdMsg_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return ca.NetSysLab.ProtocolBuffers.ForwardedMessage.internal_static_FwdMsg_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                ca.NetSysLab.ProtocolBuffers.ForwardedMessage.FwdMsg.class, ca.NetSysLab.ProtocolBuffers.ForwardedMessage.FwdMsg.Builder.class);
      }

      // Construct using ca.NetSysLab.ProtocolBuffers.ForwardedMessage.FwdMsg.newBuilder()
      private Builder() {

      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);

      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        bitField0_ = 0;
        clientMessageId_ = com.google.protobuf.ByteString.EMPTY;
        clientRequest_ = com.google.protobuf.ByteString.EMPTY;
        clientPort_ = 0;
        clientIP_ = "";
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return ca.NetSysLab.ProtocolBuffers.ForwardedMessage.internal_static_FwdMsg_descriptor;
      }

      @java.lang.Override
      public ca.NetSysLab.ProtocolBuffers.ForwardedMessage.FwdMsg getDefaultInstanceForType() {
        return ca.NetSysLab.ProtocolBuffers.ForwardedMessage.FwdMsg.getDefaultInstance();
      }

      @java.lang.Override
      public ca.NetSysLab.ProtocolBuffers.ForwardedMessage.FwdMsg build() {
        ca.NetSysLab.ProtocolBuffers.ForwardedMessage.FwdMsg result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public ca.NetSysLab.ProtocolBuffers.ForwardedMessage.FwdMsg buildPartial() {
        ca.NetSysLab.ProtocolBuffers.ForwardedMessage.FwdMsg result = new ca.NetSysLab.ProtocolBuffers.ForwardedMessage.FwdMsg(this);
        if (bitField0_ != 0) { buildPartial0(result); }
        onBuilt();
        return result;
      }

      private void buildPartial0(ca.NetSysLab.ProtocolBuffers.ForwardedMessage.FwdMsg result) {
        int from_bitField0_ = bitField0_;
        if (((from_bitField0_ & 0x00000001) != 0)) {
          result.clientMessageId_ = clientMessageId_;
        }
        if (((from_bitField0_ & 0x00000002) != 0)) {
          result.clientRequest_ = clientRequest_;
        }
        if (((from_bitField0_ & 0x00000004) != 0)) {
          result.clientPort_ = clientPort_;
        }
        if (((from_bitField0_ & 0x00000008) != 0)) {
          result.clientIP_ = clientIP_;
        }
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof ca.NetSysLab.ProtocolBuffers.ForwardedMessage.FwdMsg) {
          return mergeFrom((ca.NetSysLab.ProtocolBuffers.ForwardedMessage.FwdMsg)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(ca.NetSysLab.ProtocolBuffers.ForwardedMessage.FwdMsg other) {
        if (other == ca.NetSysLab.ProtocolBuffers.ForwardedMessage.FwdMsg.getDefaultInstance()) return this;
        if (other.getClientMessageId() != com.google.protobuf.ByteString.EMPTY) {
          setClientMessageId(other.getClientMessageId());
        }
        if (other.getClientRequest() != com.google.protobuf.ByteString.EMPTY) {
          setClientRequest(other.getClientRequest());
        }
        if (other.getClientPort() != 0) {
          setClientPort(other.getClientPort());
        }
        if (!other.getClientIP().isEmpty()) {
          clientIP_ = other.clientIP_;
          bitField0_ |= 0x00000008;
          onChanged();
        }
        this.mergeUnknownFields(other.getUnknownFields());
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        if (extensionRegistry == null) {
          throw new java.lang.NullPointerException();
        }
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              case 10: {
                clientMessageId_ = input.readBytes();
                bitField0_ |= 0x00000001;
                break;
              } // case 10
              case 18: {
                clientRequest_ = input.readBytes();
                bitField0_ |= 0x00000002;
                break;
              } // case 18
              case 29: {
                clientPort_ = input.readFixed32();
                bitField0_ |= 0x00000004;
                break;
              } // case 29
              case 34: {
                clientIP_ = input.readStringRequireUtf8();
                bitField0_ |= 0x00000008;
                break;
              } // case 34
              default: {
                if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                  done = true; // was an endgroup tag
                }
                break;
              } // default:
            } // switch (tag)
          } // while (!done)
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.unwrapIOException();
        } finally {
          onChanged();
        } // finally
        return this;
      }
      private int bitField0_;

      private com.google.protobuf.ByteString clientMessageId_ = com.google.protobuf.ByteString.EMPTY;
      /**
       * <code>bytes clientMessageId = 1;</code>
       * @return The clientMessageId.
       */
      @java.lang.Override
      public com.google.protobuf.ByteString getClientMessageId() {
        return clientMessageId_;
      }
      /**
       * <code>bytes clientMessageId = 1;</code>
       * @param value The clientMessageId to set.
       * @return This builder for chaining.
       */
      public Builder setClientMessageId(com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        clientMessageId_ = value;
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }
      /**
       * <code>bytes clientMessageId = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearClientMessageId() {
        bitField0_ = (bitField0_ & ~0x00000001);
        clientMessageId_ = getDefaultInstance().getClientMessageId();
        onChanged();
        return this;
      }

      private com.google.protobuf.ByteString clientRequest_ = com.google.protobuf.ByteString.EMPTY;
      /**
       * <code>bytes clientRequest = 2;</code>
       * @return The clientRequest.
       */
      @java.lang.Override
      public com.google.protobuf.ByteString getClientRequest() {
        return clientRequest_;
      }
      /**
       * <code>bytes clientRequest = 2;</code>
       * @param value The clientRequest to set.
       * @return This builder for chaining.
       */
      public Builder setClientRequest(com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        clientRequest_ = value;
        bitField0_ |= 0x00000002;
        onChanged();
        return this;
      }
      /**
       * <code>bytes clientRequest = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearClientRequest() {
        bitField0_ = (bitField0_ & ~0x00000002);
        clientRequest_ = getDefaultInstance().getClientRequest();
        onChanged();
        return this;
      }

      private int clientPort_ ;
      /**
       * <code>fixed32 clientPort = 3;</code>
       * @return The clientPort.
       */
      @java.lang.Override
      public int getClientPort() {
        return clientPort_;
      }
      /**
       * <code>fixed32 clientPort = 3;</code>
       * @param value The clientPort to set.
       * @return This builder for chaining.
       */
      public Builder setClientPort(int value) {

        clientPort_ = value;
        bitField0_ |= 0x00000004;
        onChanged();
        return this;
      }
      /**
       * <code>fixed32 clientPort = 3;</code>
       * @return This builder for chaining.
       */
      public Builder clearClientPort() {
        bitField0_ = (bitField0_ & ~0x00000004);
        clientPort_ = 0;
        onChanged();
        return this;
      }

      private java.lang.Object clientIP_ = "";
      /**
       * <code>string clientIP = 4;</code>
       * @return The clientIP.
       */
      public java.lang.String getClientIP() {
        java.lang.Object ref = clientIP_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          clientIP_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string clientIP = 4;</code>
       * @return The bytes for clientIP.
       */
      public com.google.protobuf.ByteString
          getClientIPBytes() {
        java.lang.Object ref = clientIP_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          clientIP_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string clientIP = 4;</code>
       * @param value The clientIP to set.
       * @return This builder for chaining.
       */
      public Builder setClientIP(
          java.lang.String value) {
        if (value == null) { throw new NullPointerException(); }
        clientIP_ = value;
        bitField0_ |= 0x00000008;
        onChanged();
        return this;
      }
      /**
       * <code>string clientIP = 4;</code>
       * @return This builder for chaining.
       */
      public Builder clearClientIP() {
        clientIP_ = getDefaultInstance().getClientIP();
        bitField0_ = (bitField0_ & ~0x00000008);
        onChanged();
        return this;
      }
      /**
       * <code>string clientIP = 4;</code>
       * @param value The bytes for clientIP to set.
       * @return This builder for chaining.
       */
      public Builder setClientIPBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        checkByteStringIsUtf8(value);
        clientIP_ = value;
        bitField0_ |= 0x00000008;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:FwdMsg)
    }

    // @@protoc_insertion_point(class_scope:FwdMsg)
    private static final ca.NetSysLab.ProtocolBuffers.ForwardedMessage.FwdMsg DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new ca.NetSysLab.ProtocolBuffers.ForwardedMessage.FwdMsg();
    }

    public static ca.NetSysLab.ProtocolBuffers.ForwardedMessage.FwdMsg getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<FwdMsg>
        PARSER = new com.google.protobuf.AbstractParser<FwdMsg>() {
      @java.lang.Override
      public FwdMsg parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        Builder builder = newBuilder();
        try {
          builder.mergeFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(builder.buildPartial());
        } catch (com.google.protobuf.UninitializedMessageException e) {
          throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(e)
              .setUnfinishedMessage(builder.buildPartial());
        }
        return builder.buildPartial();
      }
    };

    public static com.google.protobuf.Parser<FwdMsg> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<FwdMsg> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public ca.NetSysLab.ProtocolBuffers.ForwardedMessage.FwdMsg getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_FwdMsg_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_FwdMsg_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\026ForwardedMessage.proto\"^\n\006FwdMsg\022\027\n\017cl" +
      "ientMessageId\030\001 \001(\014\022\025\n\rclientRequest\030\002 \001" +
      "(\014\022\022\n\nclientPort\030\003 \001(\007\022\020\n\010clientIP\030\004 \001(\t" +
      "B0\n\034ca.NetSysLab.ProtocolBuffersB\020Forwar" +
      "dedMessageb\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_FwdMsg_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_FwdMsg_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_FwdMsg_descriptor,
        new java.lang.String[] { "ClientMessageId", "ClientRequest", "ClientPort", "ClientIP", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
